image: 'Visual Studio 2017'
environment:
  nodejs_version: '8'

install:
  - ps: Install-Product node $env:nodejs_version
  - ps: npm install -g windows-build-tools --vs2015
  - npm config -g set msvs_version 2015
  - npm install
  - npm test

build: off
